apiVersion: apps/v1
kind: Deployment
metadata:
  name: openstack-operator-controller-operator
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: operator
        env:
        - name: LEASE_DURATION
          value: "137"
        - name: RENEW_DEADLINE
          value: "107"
        - name: RETRY_PERIOD
          value: "26"
